---
- hosts: webservers
  remote_user: admin
  tasks:

  - name: Stop beachranks application
    command: daemon --name beachranks --stop
    ignore_errors: yes

  - name: Remove old beachranks sources
    command: rm -rf /home/admin/beachranks

  - name: Checkout beachranks sources
    git:
      repo: https://github.com/funduck/beach_ranks.git
      dest: /home/admin/beachranks

  - name: Update beachranks conda environment
    command: /home/admin/anaconda3/bin/conda env update -f /home/admin/beachranks/ansible/beachranks_env.yml

  - name: Start beachranks application
    command: bash /home/admin/beachranks/backend/run.sh







